### ISSUE TITLE
Support for Microsoft FluentUI System Icons

### ISSUE THREAD

**Issue by eugener** [kordamp/ikonli#100]
MS recently open-sourced great set of icons https://github.com/microsoft/fluentui-system-icons.

**Comment by aalmiray** [comment]
Thanks Eugene, we added the icon set with https://github.com/kordamp/ikonli/issues/73 and upgraded recently with https://github.com/kordamp/ikonli/issues/88

Milestone `12.0.0` has added a few more icon packs https://github.com/kordamp/ikonli/milestone/3?closed=1

If you've got any other suggestions now's the time 😏

**Comment by eugener** [comment]
My fault, did not read the docs properly.
Would be also nice to have SF Symbols from SwiftUI... not sure if it is possible license wise though.
