### ISSUE TITLE
Missing Cheat-Sheet Icons

### ISSUE THREAD

**Issue by Teragam** [kordamp/ikonli#123]
The Fontawesome5 icons in the cheat sheet are not displayed:
http://kordamp.org/ikonli/cheat-sheet-fontawesome5.html

**Comment by aalmiray** [comment]
Thank you for the report. this issue has been fixed(https://github.com/kordamp/ikonli/commit/af907f90d649883a83e3b76e1ac5af0c67e8e5c5) and will be available in the next release.
