### ISSUE TITLE
FontAwesomeBrands is broken in 12.0.0

### ISSUE THREAD

**Issue by dtoyne2** [kordamp/ikonli#125]
Hi,
After updgrading to 12.0.0 it appears that FontAwesomeBrands is broken. For example, FontAwesomeBrands.CHROME is shown as an empty box, others like FontAwesomeBrands.TWITTER are showing the wrong icon. All the other packs i'm using are working ok

**Comment by aalmiray** [comment]
Could you provide more details on your setup? Such as Java version, build tool, IDE, depedencies. Are you using the modulepath or classpath? Are you using FXML for including ikons or the API?

Here's a screenshot of ikonli-browser with FontAwesomeBrands.CHROME selected. This application defines ikons with API, no FXML.

<img width="1024" alt="ikonli-browser-fab-chrome" src="https://user-images.githubusercontent.com/13969/101287468-bac3b980-37f0-11eb-82e9-be4954a0dd4c.png">

**Comment by dtoyne2** [comment]
I'm using openjdk 15.0.1 from AdoptOpenJDK on Ubuntu 20.10, openjfx 15.0.1, intellij, maven. I am using both FXML and the API, both are getting the same results. I'm running on the module path.

It was working fine with 11.5.0 and nothing else has changed.

fab-twitter and FontAwesomeBrands.TWITTER show up as an envelope with a lightning bolt through it, which I can't see in FontAwesome brands. I'm also using material and materialdesign packs.

**Comment by aalmiray** [comment]
If `fab-twitter` is resolved without exception ten it means `org.kordamp.ikonli.fontawesome5.FontAwesomeBrandsIkonHandler` handled the iconLiteral resolution. But if the wrong icon is displayed it means the font resource or the font family is incorrect.

The font resources should be "/META-INF/resources/fontawesome5/5.15.1/fonts/fa-brands-400.ttf".
The font family should be "Font Awesome 5 Brands".

**Comment by dtoyne2** [comment]
Yes, I looked in the jar file. It seems ok

**Comment by aalmiray** [comment]
I'm at a loss here. The explanation indicates there's a problem with resource handling, as if the wrong Font file or family were in use. Dos the project code happen to be available on a public repository?

**Comment by dtoyne2** [comment]
Sorry, the code is private. When I get time I'll try to reproduce it in a separate simple app

**Comment by aalmiray** [comment]
I found an inconsistency in the `FontAwesomeBrandsIkonHandler` type. The declared font-family did not match the value found in the .ttf file. I've pushed an update which I hope solves this issue.
Could you build a local snapshot and give it a try? The readme has instructions to build a snapshot release.
Thank you.

**Comment by dtoyne2** [comment]
Yes, this works! Thanks for tracking it down

**Comment by aalmiray** [comment]
Excellent! I'll wait a few more days before posting a release, just in case there's something else that needs fixing.

**Comment by jackpeters667** [comment]
Hello @aalmiray  just checking for the progress of posting a release

**Comment by aalmiray** [comment]
I'm aiming for next week to cut a release, hoping I can get fix for https://github.com/kordamp/ikonli/issues/127 as well.
