### ISSUE TITLE
ikonli 12.0 and Scenebuilder no longer working

### ISSUE THREAD

**Issue by lanthale** [kordamp/ikonli#128]
I have switch with my Photoslide app from ikonli 11.5 to ikonli 12.0. All is working fine except in scenebuilder. I can no longer open scenebuilder fxml files without the error message that e.g. "ti-minus" cannot be instantiated.

First my thought was that the upgrade of Scenebuilder to 15 was the issue. But switching back has not helped. After remove all the 12.0 jar files and download the 11.5 jar files from maven and link them in Scenebuilder did the job.

Actually I am now in a mixed environment: pom.xml using ikonli 12.0, SceneBuilder using 11.5.
The message shows that there are access issues (reflection fails) for Scenebuilder when using 12.0.

cheers,
Clemens

**Comment by aalmiray** [comment]
This sounds like the same issues as https://github.com/kordamp/ikonli/issues/124
The next release has a fix for it.

**Comment by georgemoralis** [comment]
will it released soon?

**Comment by lanthale** [comment]
Thank you for the fast reply and the update. I will wait for the next release.
