### ISSUE TITLE
setStyle not always working

### ISSUE THREAD

**Issue by lanthale** [kordamp/ikonli#130]
I am creating in my PhotoSlide ab via code TitledPanes with an iKonli FontIcon showing the user the state of the TitledPane. After the loading of the content of the TitledPane I make the FontIcon green via code (setStyle("-fx-..."). Doing with setStyle sometimes the icon is not shown, instat a default square is displayed.

If I implement the same function via CSS (setId()) all is working fine. Overall there is a likelyhood of 70% that the setStyle method is working. This issue is also happening with 11.5 releases.

Hopefully that helps. If you need more Info you can look into the code of the CollectionsController.java in the PhotoSlide repository on https://github.com/lanthale/photoslide - method "loadDirectoryTree"

**Comment by aalmiray** [comment]
If you want to change the color of `org.kordamp.ikonli.javafx.FontIcon` why not call `setIconColor(Color)` directly?

https://github.com/kordamp/ikonli/blob/master/core/ikonli-javafx/src/main/java/org/kordamp/ikonli/javafx/FontIcon.java#L203

**Comment by lanthale** [comment]
Ok this is was I do not have in mind. This works as well. Thanks for the hint I never had in my mind! It works.
