### ISSUE TITLE
Icons as mouse cursor

### ISSUE THREAD

**Issue by joehei** [kordamp/ikonli#131]
Hi, 

first of all, you have created a really cool lib, many thanks for that.

My question is, is there a easy way to convert any icon into a mouse cursor?

Cheers

**Comment by aalmiray** [comment]
As far as I can tell this requires a subclass of https://openjfx.io/javadoc/11/javafx.graphics/javafx/scene/Cursor.html that can work with `Ikon`. There's no such class, yet. I hope that such class can be created, similar to https://openjfx.io/javadoc/11/javafx.graphics/javafx/scene/ImageCursor.html

**Comment by aalmiray** [comment]
Well the default constructor for `javax.scene.Cursor` is package private which means no additional subclasses can be made at this time. 😡

**Comment by joehei** [comment]
Das ist sehr schade. Das wäre wirklich eine cooles Feature gewesen.

Vielleicht geht das ja irgendwann in der Zukunft, wie auch immer, vielen Dank.

**Comment by aalmiray** [comment]
Indeed, there's no direct path to render an Ikon as a Cursor. However there may be a workaround: print the graphics of a FontIcon into an Image, pass that image to an ImageCursor, et voilà!

**Comment by joehei** [comment]
I will give it a try. Thanks.
