### ISSUE TITLE
Binding icon size results in exception

### ISSUE THREAD

**Issue by lanthale** [kordamp/ikonli#132]
I try to bind the iconsize to the parent (stackpane) height but getting always the following exception:
java.lang.RuntimeException: FontIcon.iconSize : A bound value cannot be set

The binding itself works perfectly but the exception is thrown, also when I call beforehand unbind on the iconsizeproperty. I do not know why the value is already bound. Setting in the constructor the iconsize works without any issues but binding throws the exception.

The binding is taking place in the constructor of that class.

Here is the code from the constructor:
`
dummyIcon = new FontIcon("fa-file-movie-o");        
dummyIcon.setIconSize(40);
dummyIcon.iconSizeProperty().unbind();
dummyIcon.iconSizeProperty().bind(rootPane.heightProperty().subtract(10));
`

**Comment by aalmiray** [comment]
As far as I can see there's no internal binding code to be found in `org.kordamp.ikonli.javafx.FontIcon`. Are you sure there's no other library/setting getting in the way?

Also, if creating a binding is a problem you could register a ChangeListener instead.

**Comment by lanthale** [comment]
I have found the issue. If I call setIconSize(40) (must be different than 8) the issue is there. If I do not set the iconsize before I bind all is working.

The following code throws the exception:
`dummyIcon = new FontIcon("fa-file-movie-o");
        dummyIcon.setIconSize(40);   
dummyIcon.iconSizeProperty().bind(rootPane.heightProperty().subtract(10));     `

And now this code is working:
`dummyIcon = new FontIcon("fa-file-movie-o"); 
dummyIcon.iconSizeProperty().bind(rootPane.heightProperty().subtract(10));     `

That means the method setIconSize is binding a value somehow.

**Comment by aalmiray** [comment]
Well the method is defined as 

https://github.com/kordamp/ikonli/blob/master/core/ikonli-javafx/src/main/java/org/kordamp/ikonli/javafx/FontIcon.java#L190-L195

While the property is created at

https://github.com/kordamp/ikonli/blob/master/core/ikonli-javafx/src/main/java/org/kordamp/ikonli/javafx/FontIcon.java#L105-L130

**Comment by lanthale** [comment]
Thank you.
So this could not be the root cause. I am searching further where the issue comes from. I am using the controlsfx GridView which uses VirtualFlow.

**Comment by aalmiray** [comment]
I think I have an idea of what may be happening. The call to `setIconSize()` changes the font, which in turn triggers `setIconSize()` again due to the listener attached to the font property on line 61.

**Comment by lanthale** [comment]
I did the following test:
Execute dummyIcon.iconSizeProperty().bind(rootPane.heightProperty().subtract(10));
-> Results in Exception

Execute  dummyIcon.iconSizeProperty().bind(rootPane.heightProperty());
-> No Exception

That means that the subtract method is causing the issue somehow.

**Comment by aalmiray** [comment]
It might be a timing issue related to the listener, as if the binding were to be in place before the listener triggers.

**Comment by lanthale** [comment]
Yes I think as well that this is the root cause.

**Comment by lanthale** [comment]
As a workaround I am using a PauseTransition with 100ms before doing the binding. Than the exception is gone and it proves your code change to be the root cause.
