### ISSUE TITLE
Style: The icons in JavaFx when use ":selected" is not working?

### ISSUE THREAD

**Issue by salmantln** [kordamp/ikonli#144]
Style the icons in JavaFx when use ":selected" is not working? Or am i doing something wrong. I try using

".button .ikonli-font-icon:selected {
-fx-icon-code: "gmi-file-download";
-fx-icon-color: red;
-fx-icon-size: 20px;
}" in my stylesheet but it doesn't seem to work.

**Comment by aalmiray** [comment]
IkonFont does not expose pseudo selectors such as `:selected`, that's the job of the Button type.

**Comment by salmantln** [comment]
But can I make sure that I change the IkonFont  color on the `.button:selected` ? like is that possible?

**Comment by aalmiray** [comment]
Refer to the JavaFX CSS guide https://docs.oracle.com/javafx/2/api/javafx/scene/doc-files/cssref.html#buttonbase
