### ISSUE TITLE
FontAwesome - plans?

### ISSUE THREAD

**Issue by elfoxus** [kordamp/ikonli#148]
Is it planned to add more styles to FontAwesome5+ icons? I mean Light or Duotone versions of icons.

**Comment by aalmiray** [comment]
Light icons are only available on the Pro version. That rules them out from inclusion in Ikonli. If you'd like to use those icons you'd have to create your own icon pack for the time being.

**Comment by elfoxus** [comment]
Late, but thank you for answer :)
