### ISSUE TITLE
Ikonli browser

### ISSUE THREAD

**Issue by MarceloRuiz** [kordamp/ikonli#37]
Hi Andres,
I made a very simple javafx app to browse all the Ikonli icons (since searching the cheat sheets was very time consuming). 
On the left side there is a toolbar with a button for each icon family and when you click on it it populates the main area with buttons for each of the icons in the family. Each of those buttons display a tooltip with the ikonli code for the icon or you can click on the button to have the code copied to the clipboard. Let me know if you are interested: I am happy to send you the code.
I attached the executable jar in case you want to see it (I just added the .zip extension so I could upload it).
Best,
Marcelo.
[IkonliBrowser.jar.zip](https://github.com/aalmiray/ikonli/files/2333775/IkonliBrowser.jar.zip)

**Comment by aalmiray** [comment]
@MarceloRuiz this is pretty cool, I like it! Would you consider contributing the code to the Ikonli project? If so you'd retain authorship :smile:

I'd also suggest to add an area at the top that displays the icon constant when any of the buttons is clicked. That way you don't have to wait for the tooltip to appear. Also, users may copy the value if the area is a non-editable textfield/textarea.

**Comment by MarceloRuiz** [comment]
@aalmiray 
I would be happy to contribute the code to the ikonli project. How should I do that exactly? 
Regarding the area for users to copy the icon constant, I could add it, but wouldn't that be redundant? The way I implemented it is that when the users clicks on any of the icons, the icon constant get copied to the user's system clipboard, so he/she can just paste whenever the value is needed. But I would be happy to add the area if you think it will help...

**Comment by aalmiray** [comment]
Great. We can start by adding another subproject to the build (like sampler-javafx). Once it's done, send me a PR with the changes :smile:

**Comment by MarceloRuiz** [comment]
Hi Andres, sorry it took me so long to get back to you. I was traveling and life is quite complicated for me until the end of the year (hopefully easier after that!).
I created a new version of the program I would like you to review. I called it "Ikonli Icon Finder" because it has now a search capability and multiple icon families can be displayed simultaneously. Tell me if you think it is ready for prime time.
Also, I have never worked with github. Should I be adding a subproject? Can you point me into the right direction?
Best,
Marcelo.

PS: As before, I just added the .zip extension to be able to upload it.
[Ikonli-Icon-Finder.jar.zip](https://github.com/aalmiray/ikonli/files/2431897/Ikonli-Icon-Finder.jar.zip)

**Comment by aalmiray** [comment]
@MarceloRuiz could you give me access to the sources?

**Comment by eitsch** [comment]
@MarceloRuiz sorry to interrupt, i just tried to get your jar to run and fell into two traps. i now know the right way, but will not really bother doing that. Please bear in mind that i am just an unimportant consumer who drove by your excellent idea. 

- first trap: Running it in Java 8 does not work  as it was compiled with java >= 9
- second trap: running it in Java 11 does not work as "someone" :smiling_imp:  decided that javafx should not be part of jdk anymore

i *understand* that i probably now need to download a java 9 to get your jar running. :crying_cat_face: 

integrating your fine idea via PR (or attaching your zipped sources) would really be a nice addition to this already fine project :+1:

**Comment by aalmiray** [comment]
Well, the README does say that Java 11 is required. If you're following the news then you should know that JavaFX 11 is now provided as a separate download. This being said, the guide could make it more explicit and perhaps provide an example on how to set it up. Meanwhile https://openjfx.io/openjfx-docs/#gradle could help as a starting point.

**Comment by eitsch** [comment]
Hi Andres @aalmiray, my comment (also the "traps") was relating to the jar/zip that @MarceloRuiz linked. I was hoping i could "just run that jar without needing to checkout/setup anything else" 

I understand that getting JavaFX set up is needed and that your README mentions the baseline of Java 11.  I also now (while writing) understand your point of view better, i guess: If i want to build/use ikonli, i need to get all this set up anyways. 

Thank you for supplying the helpful link to JavaFX / gradle info! :+1:

**Comment by ThomasDaheim** [comment]
Unfortunately, this hasn't gone anywhere? Would really be nice to have some kind of "browsing" component to allow users to select icons for themselves...

**Comment by aalmiray** [comment]
I'm working on it as we speak, an application named `ikonli-browser` which will be available right after `12.0.0` comes out (this weekend).

https://twitter.com/aalmiray/status/1325164720635207681

**Comment by ThomasDaheim** [comment]
Perfect! Exactly what I need at exactly the right moment! I'm working on adding tags to my https://github.com/ThomasDaheim/ownNoteEditor and wanted to be able to choose an icon per tag.

**Comment by ThomasDaheim** [comment]
And good to know that someone is still working to improve things in JavaFX :-)

**Comment by aalmiray** [comment]
An icon browser is already in place. Binaries currently posted to the early-access release https://github.com/kordamp/ikonli/releases/tag/12.3.0.EarlyAccess
