### ISSUE TITLE
Suppport latest Font Feather v4.16.0

### ISSUE THREAD

**Issue by timoreichen** [kordamp/ikonli#46]

**Comment by aalmiray** [comment]
Latest Feather version is 4.21.0. Unfortunately the SVG icons are produced with strokes instead of paths. This makes the Icomoon app fail to translate SVG into fonts.

**Comment by timoreichen** [comment]
oh, bad. and maybe just to the latest version which was still using svg?

**Comment by aalmiray** [comment]
I looked at the different versions. It appears no fonts are provided since version `2.0.0`.
The way to solve this is to convert all SVGs from stroke into path, then import into Icomoon, however I lack the tools to make this work for now.

**Comment by timoreichen** [comment]
ok. thanks anyway!!

**Comment by EnnoxHD** [comment]
I'll try to update to the latest version of Font Feater.
