### ISSUE TITLE
Core module identifier spelled wrong in 11.3.5

### ISSUE THREAD

**Issue by dlemmermann** [kordamp/ikonli#59]
In version 11.3.5 the "core" module uses the identifier "org.kordamp.**iconli**.core" instead of "org.kordamp.**ikonli**.core" (a "c" instead of a "k"). So the spelling, by accident, is correct .... but the code is wrong :-)

In my module-info.java I now have to write:

```
    requires org.kordamp.iconli.core;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.ikonli.materialdesign;
```

**Comment by aalmiray** [comment]
Yup, a bummer this was noticed earlier. Given that changing the module name constitutes a braking change we'll push this update for `12.0.0` which currently depends on a fix to the gradle modules plugin to be release.
