### ISSUE TITLE
What is the latest version that works in Java 8

### ISSUE THREAD

**Issue by renatoathaydes** [kordamp/ikonli#60]
Hey, @aalmiray great work on this library! I would like to use this in [LogFX](https://github.com/renatoathaydes/LogFX) but I want to keep supporting Java 8.

What would be the last version of this lib I can use with Java 8.

Cheers.

**Comment by aalmiray** [comment]
Hi @renatoathaydes, Ikonli `2.4.0` is the last version compatible with JDK8. I'm working on an option to bring back JDK8 compatibility for version `12.0.0` but it's not there yet.

**Comment by renatoathaydes** [comment]
That's fine @aalmiray it works perfectly now! This is such a valuable lib!! Thanks for making it.
I had been embedding FontAwesome in my jar by manually downloading it... With version 5, it was a nightmare to get it working in all OSs consistently - it would work in Linux, but not on Mac or Windows... then I fixed Mac, it wouldn't work on Linux... something really fishy going on... but anyway, I am not using your lib with the Themify pack and my app looks beautiful.

Just one detail: why are the CSS files and all fonts being included in the pack jar? I removed most of that from my fat jar and it still works fine (I keep only the woff file for Themify). Might be worth investigating if you could remove those (at least, I like to keep my jar slim - LogFX is still around 320KB which is quite good for all it does).

**Comment by renatoathaydes** [comment]
Correction: I keep only the `ttf` file! Not the `woff`.

**Comment by aalmiray** [comment]
I’m including all those files because technically Ikonli redistributes work made by others and thus has to be compliant with licensing. 

The good thing is that consumers can decide for themselves to repackage said resources, either using shade (Maven) or shadow (Gradle).
