### ISSUE TITLE
Add Microsoft FluentUI System Icons

### ISSUE THREAD

**Issue by EnnoxHD** [kordamp/ikonli#73]
Project: https://github.com/microsoft/fluentui-system-icons Note that it needs to be build from svg images.

**Comment by aalmiray** [comment]
What workflow did you use to transform the Feather icons from svg to font?

**Comment by EnnoxHD** [comment]
I am currently writing a small program to automate the process. I'll release it in next days.
In the mean time I used a simple Java program and https://inkscape.org/ on my Windows machine:
```java
public static void main(String[] args) throws Exception {
	System.out.println("Conversion started\n------------------");
	final String inkscape = "C:\\Program Files\\Inkscape\\bin\\inkscape.com";
	final String dir = "C:\\Users\\username\\Downloads\\feather-4.28.0\\icons\\";
	DirectoryStream<Path> fileStream = Files.newDirectoryStream(new File(dir).toPath());
	for(Path file : fileStream) {
		final ProcessBuilder processBuilder = new ProcessBuilder(inkscape, "--with-gui",
			"--actions=\"select-all;verb:StrokeToPath;verb:SelectionCombine;"
			+ "verb:FileSave;file-close;window-close\"", file.toString());
		System.out.println(processBuilder.command().stream().collect(Collectors.joining(" ")));
		final Process process = processBuilder.start();
		process.waitFor();
		Thread.sleep(1000L);
	}
	System.out.println("--------------------\nConversion completed");
}
```

**Comment by EnnoxHD** [comment]
And of cause the Icomoon App (https://icomoon.io/app/).

**Comment by EnnoxHD** [comment]
Maybe there's a way to automate this too (and save you some minutes) with some tool like FontForge (https://fontforge.org/) but I have no experience with it. The critical and time consuming work is to convert each svg like in the code above.

**Comment by EnnoxHD** [comment]
see https://github.com/EnnoxHD/glyph-creator for svg file conversion

**Comment by EnnoxHD** [comment]
see https://github.com/EnnoxHD/fluentui-system-icons-extractor for extraction of svg resource files from https://github.com/microsoft/fluentui-system-icon

**Comment by EnnoxHD** [comment]
https://github.com/microsoft/fluentui-system-icons/issues/21

**Comment by EnnoxHD** [comment]
The problem at the moment is that no all icons are technically designed consistently for glyph creation (e.g. unclosed paths). I'm currently working on some ideas to solve that.
