### ISSUE TITLE
Add Bootstrap Icons

### ISSUE THREAD

**Issue by EnnoxHD** [kordamp/ikonli#74]
Project: https://github.com/twbs/icons Note that there are currently in alpha state so we should wait until a proper 1.0.0 is out.

**Comment by aalmiray** [comment]
https://github.com/twbs/icons/pull/287

**Comment by julianjupiter** [comment]
[Bootstrap Icons v1.0.0](https://blog.getbootstrap.com/2020/08/28/bootstrap-icons-stable/) is officially out!

**Comment by aalmiray** [comment]
Font support (per twbs/icons#287) was not integrated in `1.0.0`.

**Comment by EnnoxHD** [comment]
There are also reports of having distorted icons after the conversion with icomoon. See https://github.com/twbs/icons/issues/86#issuecomment-638563200. So I guess we have to wait a bit longer for this.

**Comment by aalmiray** [comment]
Looks like bootstrap-icons `1.2.1` is out  https://github.com/twbs/icons/releases/tag/v1.2.1
