### ISSUE TITLE
Icons appear to be blurry on a Retina MacBook Pro screen

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kordamp/ikonli#77]
Running `..\..\gradlew run` from `apps/sampler-swing` on a Retina MacBook Pro shows the demo browsing app, and all the icons appear to be blurry - instead of sharp.

**Comment by aalmiray** [comment]
I noticed that as well, it may be related to icon size and will have another look. Although the FontIcon class has the following code when creating the image where the icon is drawn

                Graphics2D g2 = (Graphics2D) buffer.getGraphics();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);

**Comment by nicolaecismaru** [comment]
The icon is no longer blurry on HiDPI screens if it is painted directly to the Graphics object instead of painting it from the cached BufferedImage buffer.

[ikonli-77.patch.zip](https://github.com/kordamp/ikonli/files/6346720/ikonli-77.patch.zip)

**Comment by aalmiray** [comment]
Thanks! removing the double-buffering does solve the issue.
