### ISSUE TITLE
Get all icons API

### ISSUE THREAD

**Issue by piusalfred** [kordamp/ikonli#78]
In case I want to receive an Iterable List of all Material Icons. Can something like this be done?
```java
List<FontIcon> materialIcons = Ikonli.getAllIcons(FontIcon.MATERIAL_ICONS);
```

**Comment by aalmiray** [comment]
There's no need for such API. All ikons are defined using dedicated enums, simply query their `.values()` for a given enum.

**Comment by piusalfred** [comment]
Thanks. I am trying to create a little Ikonli Icons Browser here. [https://github.com/piusalfred/ikonfx](url)
