### ISSUE TITLE
Using private .ttf icons

### ISSUE THREAD

**Issue by PoslavskySV** [kordamp/ikonli#81]
Hi,

thanks for the useful library. I want to use my private .ttf icons in the project and it seems that the only way to do this using public APIs is using `ServiceProviderInterface`. This is not very convenient because of the need to add somehow additional files to the JAR. On the other hand, probably the much easier way would be just to register my custom `IkonHandler` directly in `IkonResolver`. This can be possible if you make `IkonResolver.HANDLERS` public or add public method e.g. `IkonResolver.registerHandler(IkonHandler)`. Does it make sense? (if yes, I can make a PR with appropriate changes)

Thanks!
Stanislav

**Comment by aalmiray** [comment]
Hi! Good suggestion. I prefer the register method option. I'm a fan of symmetric APIs thus a companion unregister method would be needed. The tricky parts are:

1. no handler loaded via ServiceLoader may be unregistered, that is, if devicons is loaded via classpath then no effect occurs (other than a warning or an IllegalArgumentException) when unregister(DeviconsHandler) is invoked. 
2. no handler loaded via ServiceLoader may be overwritten by a register handler, that is, if devicons is loaded via classpath then register(MyDeviconsHandler) should warn or throw IllegalArgumentException)

I think the option between warn and throwing an exception may be controlled using a System property `org.kordamp.ikonli.strict` with default value `true`, that is, throw exception.

**Comment by PoslavskySV** [comment]
Thanks for the advice! Just made a PR, please have a look on it, when you'll have time.

**Comment by PoslavskySV** [comment]
Fixed via #82
