### ISSUE TITLE
Java: error: release version 5 not supported

### ISSUE THREAD

**Issue by marcosautto** [kordamp/ikonli#84]
I'm trying to install Ikonli in my project, but I got the error in title.
I already added required dependencies in my pom.xml and I'm using Java 11 with IntelliJ Idea IDE.
Since Ikonli requires Java 11+, am I missing something?

**Comment by aalmiray** [comment]
Well it's hard to tell without having a look at the `pom.xml`. Did you explicitly set values for source, target, and release properties of the maven-compiler plugin to match JDK? Otherwise Maven picks up JDK5 by default

**Comment by marcosautto** [comment]
This is my pom.xml
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>groupId</groupId>
    <artifactId>icontest</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-javafx</artifactId>
            <version>11.5.0</version>
        </dependency>

    <dependency>
        <groupId>org.kordamp.ikonli</groupId>
        <artifactId>ikonli-materialdesign-pack</artifactId>
        <version>11.5.0</version>
    </dependency>
    </dependencies>


</project>`

**Comment by aalmiray** [comment]
First things first, I was able to run a build on the command line (OSX, JDK14)

    $ cat pom.xml 
    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        <modelVersion>4.0.0</modelVersion>
    
        <groupId>groupId</groupId>
        <artifactId>icontest</artifactId>
        <version>1.0-SNAPSHOT</version>
    
        <properties>
            <maven.compiler.source>11</maven.compiler.source>
            <maven.compiler.target>11</maven.compiler.target>
        </properties>
    
        <dependencies>
            <dependency>
                <groupId>org.kordamp.ikonli</groupId>
                <artifactId>ikonli-javafx</artifactId>
                <version>11.5.0</version>
            </dependency>
    
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-materialdesign-pack</artifactId>
            <version>11.5.0</version>
        </dependency>
        </dependencies>
    </project>
    $ mvn --version
    Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
    Maven home: /Users/aalmiray/.sdkman/candidates/maven/current
    Java version: 14, vendor: AdoptOpenJDK, runtime: /Users/aalmiray/.sdkman/candidates/java/14.0.0.hs-adpt
    Default locale: en_CH, platform encoding: UTF-8
    OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "mac"
    $ mvn dependency:tree
    [INFO] Scanning for projects...
    [INFO] 
    [INFO] --------------------------< groupId:icontest >--------------------------
    [INFO] Building icontest 1.0-SNAPSHOT
    [INFO] --------------------------------[ jar ]---------------------------------
    [INFO] 
    [INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ icontest ---
    [INFO] groupId:icontest:jar:1.0-SNAPSHOT
    [INFO] +- org.kordamp.ikonli:ikonli-javafx:jar:11.5.0:compile
    [INFO] |  \- org.kordamp.ikonli:ikonli-core:jar:11.5.0:compile
    [INFO] \- org.kordamp.ikonli:ikonli-materialdesign-pack:jar:11.5.0:compile
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time:  0.549 s
    [INFO] Finished at: 2020-08-25T20:49:12+02:00
    [INFO] ------------------------------------------------------------------------
    $ mvn package
    [INFO] Scanning for projects...
    [INFO] 
    [INFO] --------------------------< groupId:icontest >--------------------------
    [INFO] Building icontest 1.0-SNAPSHOT
    [INFO] --------------------------------[ jar ]---------------------------------
    [INFO] 
    [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ icontest ---
    [WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
    [INFO] skip non existing resourceDirectory /private/tmp/src/main/resources
    [INFO] 
    [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ icontest ---
    [INFO] No sources to compile
    [INFO] 
    [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ icontest ---
    [WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
    [INFO] skip non existing resourceDirectory /private/tmp/src/test/resources
    [INFO] 
    [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ icontest ---
    [INFO] No sources to compile
    [INFO] 
    [INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ icontest ---
    [INFO] No tests to run.
    [INFO] 
    [INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ icontest ---
    [WARNING] JAR will be empty - no content was marked for inclusion!
    [INFO] Building jar: /private/tmp/target/icontest-1.0-SNAPSHOT.jar
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time:  2.358 s
    [INFO] Finished at: 2020-08-25T20:49:21+02:00
    [INFO] ------------------------------------------------------------------------

Next, imported the project in IntelliJ (2019.2 Ultimate) and set the project's JDK to IJ's 11, it also works.

**Comment by marcosautto** [comment]
I found out that problem was my Maven config.
Feel sorry to have opened an issue for this, I'm stupid.
You can delete this issue.
